name: scheduler
version: "3.7"
services:
  postgres:
    container_name: scheduler-postgres
    image: postgres:15-alpine
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "scheduler"
      POSTGRES_USER: "scheduler"
      POSTGRES_PASSWORD: "scheduler"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
      
volumes:
  pgdata:
