# Generated by Django 5.0.1 on 2024-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queue_at", models.DateTimeField(null=True)),
                ("queued", models.BooleanField()),
                ("func", models.CharField(max_length=255)),
                ("args", models.BinaryField()),
                ("kargs", models.BinaryField()),
            ],
        ),
    ]
